-- =========================================================
-- LEGION BIAŁYSTOK — KOMPLETNY SCHEMAT SUPABASE
-- Idempotentny: można uruchamiać ponownie w SQL Editor.
-- =========================================================

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  permissions text[] not null default '{}'::text[],
  is_full_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.articles (
  id bigint primary key,
  image text not null default '',
  published_at timestamptz,
  status text not null default 'draft' check (status in ('draft','published')),
  tags text[] not null default '{}'::text[],
  translations jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.stories (
  id bigint primary key,
  title text not null default '',
  image text not null default '',
  article_url text not null default '',
  status text not null default 'active' check (status in ('active','inactive')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.players (
  id bigint primary key,
  first_name text not null default '',
  last_name text not null default '',
  shirt_number integer,
  position text not null default 'midfielder' check (position in ('goalkeeper','defender','midfielder','forward')),
  birth_date date,
  previous_club text not null default '',
  nationality text not null default '',
  nationality_code text not null default '',
  height_cm integer,
  joined_at date,
  team text not null check (team in ('first','second','academy')),
  academy_group text,
  status text not null default 'active' check (status in ('active','inactive')),
  translations jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.people (
  id bigint primary key,
  first_name text not null default '',
  last_name text not null default '',
  category text not null default 'staff' check (category in ('board','staff','academy','office')),
  role text not null default '',
  department text not null default '',
  email text not null default '',
  phone text not null default '',
  status text not null default 'active' check (status in ('active','inactive')),
  sort_order integer not null default 0,
  translations jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.people add column if not exists sort_order integer not null default 0;

create table if not exists public.gallery (
  id bigint primary key,
  image text not null default '',
  alt text not null default '',
  caption text not null default '',
  sort_order integer not null default 0,
  status text not null default 'active' check (status in ('active','inactive')),
  translations jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint primary key,
  title text not null default '',
  category text not null default 'Klub',
  description text not null default '',
  file_url text not null default '',
  file_name text not null default '',
  published_at timestamptz,
  status text not null default 'active' check (status in ('active','inactive')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.seasons (
  name text primary key,
  active boolean not null default false
);

create table if not exists public.standings (
  id bigint generated by default as identity primary key,
  season text not null references public.seasons(name) on update cascade on delete cascade,
  position integer not null default 0,
  team text not null,
  logo text not null default '',
  played integer not null default 0,
  wins integer not null default 0,
  draws integer not null default 0,
  losses integer not null default 0,
  goals_for integer not null default 0,
  goals_against integer not null default 0,
  points integer not null default 0,
  form text[] not null default '{}'::text[],
  unique (season, team)
);

create table if not exists public.matches (
  kind text primary key check (kind in ('last','next')),
  date timestamptz,
  home_team text not null default '',
  away_team text not null default '',
  home_logo text not null default '',
  away_logo text not null default '',
  home_score integer,
  away_score integer,
  competition text not null default '',
  venue text not null default ''
);

create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);

-- ---------------------------------------------------------
-- Pomocnicze funkcje uprawnień
-- ---------------------------------------------------------
create or replace function public.is_full_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select p.is_full_admin from public.admin_profiles p where p.user_id = auth.uid()), false);
$$;

create or replace function public.has_admin_permission(permission_name text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select p.is_full_admin or permission_name = any(p.permissions)
    from public.admin_profiles p
    where p.user_id = auth.uid()
  ), false);
$$;

revoke all on function public.is_full_admin() from public;
revoke all on function public.has_admin_permission(text) from public;
grant execute on function public.is_full_admin() to authenticated;
grant execute on function public.has_admin_permission(text) to authenticated;

-- ---------------------------------------------------------
-- RLS
-- ---------------------------------------------------------
alter table public.admin_profiles enable row level security;
alter table public.articles enable row level security;
alter table public.stories enable row level security;
alter table public.players enable row level security;
alter table public.people enable row level security;
alter table public.gallery enable row level security;
alter table public.documents enable row level security;
alter table public.seasons enable row level security;
alter table public.standings enable row level security;
alter table public.matches enable row level security;
alter table public.settings enable row level security;

-- Profile: użytkownik może odczytać własny profil. Zarządzanie profilami robi Edge Function service_role.
drop policy if exists "read own admin profile" on public.admin_profiles;
create policy "read own admin profile" on public.admin_profiles for select to authenticated using (user_id = auth.uid());

-- Articles
drop policy if exists "public published articles" on public.articles;
create policy "public published articles" on public.articles for select to anon using (status = 'published');
drop policy if exists "admin read articles" on public.articles;
create policy "admin read articles" on public.articles for select to authenticated using (public.has_admin_permission('articles'));
drop policy if exists "admin write articles" on public.articles;
create policy "admin write articles" on public.articles for all to authenticated using (public.has_admin_permission('articles')) with check (public.has_admin_permission('articles'));

-- Stories
drop policy if exists "public active stories" on public.stories;
create policy "public active stories" on public.stories for select to anon using (status = 'active');
drop policy if exists "admin read stories" on public.stories;
create policy "admin read stories" on public.stories for select to authenticated using (public.has_admin_permission('stories'));
drop policy if exists "admin write stories" on public.stories;
create policy "admin write stories" on public.stories for all to authenticated using (public.has_admin_permission('stories')) with check (public.has_admin_permission('stories'));

-- Players
drop policy if exists "public active players" on public.players;
create policy "public active players" on public.players for select to anon using (status = 'active');
drop policy if exists "admin read players" on public.players;
create policy "admin read players" on public.players for select to authenticated using (
  public.has_admin_permission('team1') or public.has_admin_permission('team2') or public.has_admin_permission('academy')
);
drop policy if exists "admin write players" on public.players;
create policy "admin write players" on public.players for all to authenticated
using (
  (team='first' and public.has_admin_permission('team1')) or
  (team='second' and public.has_admin_permission('team2')) or
  (team='academy' and public.has_admin_permission('academy'))
)
with check (
  (team='first' and public.has_admin_permission('team1')) or
  (team='second' and public.has_admin_permission('team2')) or
  (team='academy' and public.has_admin_permission('academy'))
);

-- People
drop policy if exists "public active people" on public.people;
create policy "public active people" on public.people for select to anon using (status = 'active');
drop policy if exists "admin read people" on public.people;
create policy "admin read people" on public.people for select to authenticated using (public.has_admin_permission('people'));
drop policy if exists "admin write people" on public.people;
create policy "admin write people" on public.people for all to authenticated using (public.has_admin_permission('people')) with check (public.has_admin_permission('people'));

-- Gallery
drop policy if exists "public active gallery" on public.gallery;
create policy "public active gallery" on public.gallery for select to anon using (status = 'active');
drop policy if exists "admin read gallery" on public.gallery;
create policy "admin read gallery" on public.gallery for select to authenticated using (public.has_admin_permission('gallery'));
drop policy if exists "admin write gallery" on public.gallery;
create policy "admin write gallery" on public.gallery for all to authenticated using (public.has_admin_permission('gallery')) with check (public.has_admin_permission('gallery'));

-- Documents
drop policy if exists "public active documents" on public.documents;
create policy "public active documents" on public.documents for select to anon using (status = 'active');
drop policy if exists "admin read documents" on public.documents;
create policy "admin read documents" on public.documents for select to authenticated using (public.has_admin_permission('documents'));
drop policy if exists "admin write documents" on public.documents;
create policy "admin write documents" on public.documents for all to authenticated using (public.has_admin_permission('documents')) with check (public.has_admin_permission('documents'));

-- Seasons / standings
drop policy if exists "public read seasons" on public.seasons;
create policy "public read seasons" on public.seasons for select to anon, authenticated using (true);
drop policy if exists "admin write seasons" on public.seasons;
create policy "admin write seasons" on public.seasons for all to authenticated using (public.has_admin_permission('seasons') or public.has_admin_permission('table')) with check (public.has_admin_permission('seasons') or public.has_admin_permission('table'));

drop policy if exists "public read standings" on public.standings;
create policy "public read standings" on public.standings for select to anon, authenticated using (true);
drop policy if exists "admin write standings" on public.standings;
create policy "admin write standings" on public.standings for all to authenticated using (public.has_admin_permission('table')) with check (public.has_admin_permission('table'));

-- Matches
drop policy if exists "public read matches" on public.matches;
create policy "public read matches" on public.matches for select to anon, authenticated using (true);
drop policy if exists "admin write matches" on public.matches;
create policy "admin write matches" on public.matches for all to authenticated using (public.has_admin_permission('matches')) with check (public.has_admin_permission('matches'));

-- Settings (publicznie tylko kontakt)
drop policy if exists "public read contact setting" on public.settings;
create policy "public read contact setting" on public.settings for select to anon, authenticated using (key = 'contact_email');
drop policy if exists "admin write contact setting" on public.settings;
create policy "admin write contact setting" on public.settings for all to authenticated using (key='contact_email' and public.has_admin_permission('contact')) with check (key='contact_email' and public.has_admin_permission('contact'));

-- Dane startowe
insert into public.seasons(name,active) values ('2026/2027',true)
on conflict (name) do nothing;

insert into public.settings(key,value) values ('contact_email','kontakt@legionbialystok.pl')
on conflict (key) do nothing;
